## String Manipulations/Operations

In [1]:
import pandas as pd

In [12]:
data = {
    "Name":["Ali    ","Bob","Charlie","David"],
    "Email":['ali@gmail.com','bob@gmail.com','charlie@gmail.com','david@gmail.com']
}
df = pd.DataFrame(data)
df

      Name              Email
0  Ali          ali@gmail.com
1      Bob      bob@gmail.com
2  Charlie  charlie@gmail.com
3    David    david@gmail.com

In [15]:
#Changing case
print(df['Name'].str.lower())
print("---------------------------")
print(df["Name"].str.upper())
print("----------------------------")
print(df["Name"].str.title())
print("----------------------------")
print(df["Name"].str.strip())

0    ali
1        bob
2    charlie
3      david
Name: Name, dtype: object
---------------------------
0    ALI
1        BOB
2    CHARLIE
3      DAVID
Name: Name, dtype: object
----------------------------
0    Ali
1        Bob
2    Charlie
3      David
Name: Name, dtype: object
----------------------------
0        Ali
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

In [17]:
#slcing
df["Name"].str.strip().str[:2]

0    Al
1    Bo
2    Ch
3    Da
Name: Name, dtype: object

In [18]:
df["Email"].str.split('@').str[1]

0    gmail.com
1    gmail.com
2    gmail.com
3    gmail.com
Name: Email, dtype: object

In [19]:
df["Email"].str.contains('gmail') # check substring

0    True
1    True
2    True
3    True
Name: Email, dtype: bool

In [20]:
df["Name"].str.strip().str.startswith("A")

0     True
1    False
2    False
3    False
Name: Name, dtype: bool

In [23]:
df["Name"].str.strip().str.endswith("e")

0    False
1    False
2     True
3    False
Name: Name, dtype: bool

In [27]:
# Replacing
df["Email"].str.replace("gmail","yahoo")

0        ali@yahoo.com
1        bob@yahoo.com
2    charlie@yahoo.com
3      david@yahoo.com
Name: Email, dtype: object

In [28]:
# Splitting and joining
df["Email"].str.split("@") # Split text

0        [ali, gmail.com]
1        [bob, gmail.com]
2    [charlie, gmail.com]
3      [david, gmail.com]
Name: Email, dtype: object

In [29]:
#joining
df["Name"].str.strip().str.cat(sep = '-')

'Ali-Bob-Charlie-David'

In [30]:
df["Name"].str.len()

0    7
1    3
2    7
3    5
Name: Name, dtype: int64

## Date time Manipulation

In [31]:
data = {
    "Student":["Ali","Bob","Charlie","David"],
    "JoinDate":["2023-01-15","2023-03-22","2023-05-10","2023-07-01"],
    "Lastlogin":["2023-09-01 10:30:00","2023-09-05 15:45:00","2023-09-07 09:15:00","2023-09-10 20:00:00"]
}
df = pd.DataFrame(data)
df

   Student    JoinDate            Lastlogin
0      Ali  2023-01-15  2023-09-01 10:30:00
1      Bob  2023-03-22  2023-09-05 15:45:00
2  Charlie  2023-05-10  2023-09-07 09:15:00
3    David  2023-07-01  2023-09-10 20:00:00

In [34]:
df["JoinDate"] = pd.to_datetime(df["JoinDate"])
df["Lastlogin"] = pd.to_datetime(df["Lastlogin"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Student    4 non-null      object
 1   JoinDate   4 non-null      datetime64[ns]
 2   Lastlogin  4 non-null      datetime64[ns]
dtypes: datetime64[ns](2), object(1)
memory usage: 228.0+ bytes

In [42]:
#Extract year month day
print(df["JoinDate"].dt.year) #print year
print("---------------------------")
print(df["JoinDate"].dt.month) #
print("----------------------------")
print(df["JoinDate"].dt.day)
print("----------------------------")
print(df["JoinDate"].dt.weekday)
print("-----------------------------")
print(df["JoinDate"].dt.day_name())

0    2023
1    2023
2    2023
3    2023
Name: JoinDate, dtype: int32
---------------------------
0    1
1    3
2    5
3    7
Name: JoinDate, dtype: int32
----------------------------
0    15
1    22
2    10
3     1
Name: JoinDate, dtype: int32
----------------------------
0    6
1    2
2    2
3    5
Name: JoinDate, dtype: int32
-----------------------------
0       Sunday
1    Wednesday
2    Wednesday
3     Saturday
Name: JoinDate, dtype: object

In [43]:
#difference between dates
df["Lastlogin"] - df["JoinDate"]

0   229 days 10:30:00
1   167 days 15:45:00
2   120 days 09:15:00
3    71 days 20:00:00
dtype: timedelta64[ns]

In [45]:
(df["Lastlogin"] - df["JoinDate"]).dt.days

0    229
1    167
2    120
3     71
dtype: int64

In [48]:
print(df["JoinDate"] + pd.Timedelta(days = 30))
print("----------------------------")
print(df["JoinDate"] - pd.Timedelta(days = 30))

0   2023-02-14
1   2023-04-21
2   2023-06-09
3   2023-07-31
Name: JoinDate, dtype: datetime64[ns]
----------------------------
0   2022-12-16
1   2023-02-20
2   2023-04-10
3   2023-06-01
Name: JoinDate, dtype: datetime64[ns]

In [50]:
print(df["Lastlogin"].dt.hour)
print("-------------------")
print(df["Lastlogin"].dt.minute)
print("---------------------")
print(df["Lastlogin"].dt.second)

0    10
1    15
2     9
3    20
Name: Lastlogin, dtype: int32
-------------------
0    30
1    45
2    15
3     0
Name: Lastlogin, dtype: int32
---------------------
0    0
1    0
2    0
3    0
Name: Lastlogin, dtype: int32

In [51]:
df["JoinDate"].dt.strftime("%Y/%m/%d")

0    2023/01/15
1    2023/03/22
2    2023/05/10
3    2023/07/01
Name: JoinDate, dtype: object

In [52]:
df[df["JoinDate"] > "2023-03-01"]

   Student   JoinDate           Lastlogin
1      Bob 2023-03-22 2023-09-05 15:45:00
2  Charlie 2023-05-10 2023-09-07 09:15:00
3    David 2023-07-01 2023-09-10 20:00:00