In [58]:
import pandas as pd

In [60]:
import warnings 
warnings.filterwarnings('ignore')

## apply()

In [85]:
data = {
    "Name":["chandu","prasad","rohith","vinod"],
    "Department":["HR","IT","Finance","IT"],
    "Salary":[50000,60000,55000,70000],
    "Joining_Year":[2019,2020,2018,2021]
}
df = pd.DataFrame(data)
df

     Name Department  Salary  Joining_Year
0  chandu         HR   50000          2019
1  prasad         IT   60000          2020
2  rohith    Finance   55000          2018
3   vinod         IT   70000          2021

In [86]:
df["Updated_Salaries"] = df["Salary"].apply(lambda x:x+5000)
df

     Name Department  Salary  Joining_Year  Updated_Salaries
0  chandu         HR   50000          2019             55000
1  prasad         IT   60000          2020             65000
2  rohith    Finance   55000          2018             60000
3   vinod         IT   70000          2021             75000

In [87]:
def salary_category(salary):
    if salary >= 60000:
        return "High"
    else:
        return "Low"
df["Salary_Category"] = df["Salary"].apply(salary_category)
df

     Name Department  Salary  Joining_Year  Updated_Salaries Salary_Category
0  chandu         HR   50000          2019             55000             Low
1  prasad         IT   60000          2020             65000            High
2  rohith    Finance   55000          2018             60000             Low
3   vinod         IT   70000          2021             75000            High

In [88]:
import datetime as dt
dt.datetime.now()

datetime.datetime(2026, 2, 17, 10, 26, 25, 340485)

In [89]:
current_year = dt.datetime.now().year
df["Experience"] = df.apply(lambda row : current_year - row["Joining_Year"],axis = 1)
df

,Name,Department,Salary,Joining_Year,Updated_Salaries,Salary_Category,Experience
0,chandu,HR,50000,2019,55000,Low,7
1,prasad,IT,60000,2020,65000,High,6
2,rohith,Finance,55000,2018,60000,Low,8
3,vinod,IT,70000,2021,75000,High,5

In [90]:
df["Name_upper"] = df["Name"].apply(str.upper)
df

,Name,Department,Salary,Joining_Year,Updated_Salaries,Salary_Category,Experience,Name_upper
0,chandu,HR,50000,2019,55000,Low,7,CHANDU
1,prasad,IT,60000,2020,65000,High,6,PRASAD
2,rohith,Finance,55000,2018,60000,Low,8,ROHITH
3,vinod,IT,70000,2021,75000,High,5,VINOD

In [91]:
df["Dept_len"] = df["Department"].str.len()
df

,Name,Department,Salary,Joining_Year,Updated_Salaries,Salary_Category,Experience,Name_upper,Dept_len
0,chandu,HR,50000,2019,55000,Low,7,CHANDU,2
1,prasad,IT,60000,2020,65000,High,6,PRASAD,2
2,rohith,Finance,55000,2018,60000,Low,8,ROHITH,7
3,vinod,IT,70000,2021,75000,High,5,VINOD,2

In [92]:
def added_salary(Salary):
    Salary+= 5000
    return Salary


df["New_salary"] = df["Salary"].apply(added_salary)
df

,Name,Department,Salary,Joining_Year,Updated_Salaries,Salary_Category,Experience,Name_upper,Dept_len,New_salary
0,chandu,HR,50000,2019,55000,Low,7,CHANDU,2,55000
1,prasad,IT,60000,2020,65000,High,6,PRASAD,2,65000
2,rohith,Finance,55000,2018,60000,Low,8,ROHITH,7,60000
3,vinod,IT,70000,2021,75000,High,5,VINOD,2,75000

In [93]:
data = {
    "Name":["chandu","prasad","rohith","vinod"],
    "Department":["HR","IT","Finance","IT"],
    "Salary":[50000,60000,55000,70000],
    "Joining_Year":[2019,2020,2018,2021]
}
df = pd.DataFrame(data)
df

     Name Department  Salary  Joining_Year
0  chandu         HR   50000          2019
1  prasad         IT   60000          2020
2  rohith    Finance   55000          2018
3   vinod         IT   70000          2021

In [94]:
df["Updated_salary"] = df["Salary"].map(lambda x: x+5000)
df

     Name Department  Salary  Joining_Year  Updated_salary
0  chandu         HR   50000          2019           55000
1  prasad         IT   60000          2020           65000
2  rohith    Finance   55000          2018           60000
3   vinod         IT   70000          2021           75000

In [95]:
# map departmnet names to codes

dept_map = {"HR":"D1","IT":"D2","Finance":"D3"}
df["Dept_code"] = df["Department"].map(dept_map)
df

     Name Department  Salary  Joining_Year  Updated_salary Dept_code
0  chandu         HR   50000          2019           55000        D1
1  prasad         IT   60000          2020           65000        D2
2  rohith    Finance   55000          2018           60000        D3
3   vinod         IT   70000          2021           75000        D2

In [96]:
bonus = pd.Series([500,600,550,700],index = [0,1,2,3])
df["Bonus"] = df.index.map(bonus)
df

     Name Department  Salary  Joining_Year  Updated_salary Dept_code  Bonus
0  chandu         HR   50000          2019           55000        D1    500
1  prasad         IT   60000          2020           65000        D2    600
2  rohith    Finance   55000          2018           60000        D3    550
3   vinod         IT   70000          2021           75000        D2    700

In [97]:
data = {
    "Salary":[50000,60000,55000,70000],
    "Numbers":[2019,2020,2018,2021]
}
df = pd.DataFrame(data)
df

   Salary  Numbers
0   50000     2019
1   60000     2020
2   55000     2018
3   70000     2021

In [98]:
data = {
    "Name":["chandu","prasad","rohith","vinod"],
    "Department":["HR","IT","Finance","IT"],
    "Salary":[50000,60000,55000,70000],
    "Bonus":[5000,6000,5500,6000]
}
df = pd.DataFrame(data)
df

     Name Department  Salary  Bonus
0  chandu         HR   50000   5000
1  prasad         IT   60000   6000
2  rohith    Finance   55000   5500
3   vinod         IT   70000   6000

In [99]:
def add_numeric(x):
    if isinstance(x,(int , float)):
        return x + 1000
    return x

df2 = df.applymap(add_numeric)
df2

     Name Department  Salary  Bonus
0  chandu         HR   51000   6000
1  prasad         IT   61000   7000
2  rohith    Finance   56000   6500
3   vinod         IT   71000   7000

In [100]:
def to_upper(x):
    if isinstance(x,str):
        return x.upper()
    return x


df3 = df.applymap(to_upper)
df3

     Name Department  Salary  Bonus
0  CHANDU         HR   50000   5000
1  PRASAD         IT   60000   6000
2  ROHITH    FINANCE   55000   5500
3   VINOD         IT   70000   6000

In [101]:
def high(x):
    if isinstance(x,(int,float)) and x > 60000:
        if x >7000:
            return "High"
    return x

df4 = df.applymap(high)
df4

     Name Department Salary  Bonus
0  chandu         HR  50000   5000
1  prasad         IT  60000   6000
2  rohith    Finance  55000   5500
3   vinod         IT   High   6000

In [102]:
df_upper = df.applymap(lambda x : x.upper() if isinstance(x,str) else x)
df_upper

     Name Department  Salary  Bonus
0  CHANDU         HR   50000   5000
1  PRASAD         IT   60000   6000
2  ROHITH    FINANCE   55000   5500
3   VINOD         IT   70000   6000

## window functions

## Rolling() and Expanding()

In [104]:
sales = pd.Series([10,20,30,40,50])
sales

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [108]:
print("Rolling:\n", sales.rolling(3).mean())
print("----------------------------------")
print("Expanding:\n", sales.expanding().mean())

Rolling:
 0     NaN
1     NaN
2    20.0
3    30.0
4    40.0
dtype: float64
----------------------------------
Expanding:
 0    10.0
1    15.0
2    20.0
3    25.0
4    30.0
dtype: float64

In [109]:
import json

In [111]:
employee_data = [
    {"Employee_ID":1,"Name":"John","Department":"HR","Salary":50000},
    {"Employee_ID":2,"Name":"Ram","Department":"Finance","Salary":50000},
    {"Employee_ID":3,"Name":"David","Department":"IT","Salary":50000}
]

In [112]:
# save this data to json

with open("employees.json","w") as f:
    json.dump(employee_data,f,indent=4)

In [115]:
#df = pd.DataFrame(employee_data)
#df

In [118]:
with open("employees.json","r") as f:
    loaded_data = json.load(f)

In [119]:
loaded_data

[{'Employee_ID': 1, 'Name': 'John', 'Department': 'HR', 'Salary': 50000},
 {'Employee_ID': 2, 'Name': 'Ram', 'Department': 'Finance', 'Salary': 50000},
 {'Employee_ID': 3, 'Name': 'David', 'Department': 'IT', 'Salary': 50000}]

In [120]:
df = pd.read_json("employees.json")
df

   Employee_ID   Name Department  Salary
0            1   John         HR   50000
1            2    Ram    Finance   50000
2            3  David         IT   50000

In [121]:
df.to_json("emp_output.json",orient = "records",indent = 4)

In [127]:
json_string = '{"Employee_ID": 4, "Name": "Ramesh", "Department": "Finance", "Salary": 65000}'
parsed = json.loads(json_string)
print(parsed)

{'Employee_ID': 4, 'Name': 'Ramesh', 'Department': 'Finance', 'Salary': 65000}