## Index Based Merging

In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    "EmpName":["A","B","C","D"],
    "Dept":["HR","IT","Finance","Sales"]
               
},index = [101,102,103,104])

salaries = pd.DataFrame({
    "Salary":[50000,60000,55000,45000]
},index = [101,102,103,105])
print(employees)
print("----------------------")
print(salaries)

    EmpName     Dept
101       A       HR
102       B       IT
103       C  Finance
104       D    Sales
----------------------
     Salary
101   50000
102   60000
103   55000
105   45000

In [3]:
#Inner Join
inner_merge = employees.merge(salaries,left_index = True,right_index = True , how = 'inner')
inner_merge

    EmpName     Dept  Salary
101       A       HR   50000
102       B       IT   60000
103       C  Finance   55000

In [4]:
# Left join
left_merge = employees.merge(salaries,left_index = True,right_index = True , how = 'left')
left_merge

    EmpName     Dept   Salary
101       A       HR  50000.0
102       B       IT  60000.0
103       C  Finance  55000.0
104       D    Sales      NaN

In [5]:
# Right join
right_merge = employees.merge(salaries,left_index = True,right_index = True , how = 'right')
right_merge

    EmpName     Dept  Salary
101       A       HR   50000
102       B       IT   60000
103       C  Finance   55000
105     NaN      NaN   45000

In [6]:
# Outer join
outer_merge = employees.merge(salaries,left_index = True,right_index = True , how = 'outer')
outer_merge

    EmpName     Dept   Salary
101       A       HR  50000.0
102       B       IT  60000.0
103       C  Finance  55000.0
104       D    Sales      NaN
105     NaN      NaN  45000.0

## Data Cleaning/Handling Missing Data

In [7]:
data = {
    "Customer":["A","B","C","D","E"],
    "Age":[25,None,30,None,28],
    "City":["New York","Los Angels",None,"Chicago",None],
    "Purchase":[200,None,150,300,None]
}
df = pd.DataFrame(data)
df

  Customer   Age        City  Purchase
0        A  25.0    New York     200.0
1        B   NaN  Los Angels       NaN
2        C  30.0        None     150.0
3        D   NaN     Chicago     300.0
4        E  28.0        None       NaN

In [8]:
# Detect Missing values
# df.isnull()True is missing values , False = Non missing values
print(df.isnull())

   Customer    Age   City  Purchase
0     False  False  False     False
1     False   True  False      True
2     False  False   True     False
3     False   True  False     False
4     False  False   True      True

In [9]:
# count Missing values in each column
df.isnull().sum()

Customer    0
Age         2
City        2
Purchase    2
dtype: int64

In [10]:
# Total missing vlaues in dataset
df.isnull().sum().sum()

np.int64(6)

In [11]:
# Detect non missing vlaues
# df.notnull()False is missing values , True = Non missing values
df.notnull()

   Customer    Age   City  Purchase
0      True   True   True      True
1      True  False   True     False
2      True   True  False      True
3      True  False   True      True
4      True   True  False     False

In [12]:
#Count of non missing values in each column
df.notnull().sum()

Customer    5
Age         3
City        3
Purchase    3
dtype: int64

In [13]:
# Total non nmissing values in dataset
df.notnull().sum().sum()

np.int64(14)

In [14]:
df1 = df.fillna(0)
df1

  Customer   Age        City  Purchase
0        A  25.0    New York     200.0
1        B   0.0  Los Angels       0.0
2        C  30.0           0     150.0
3        D   0.0     Chicago     300.0
4        E  28.0           0       0.0

In [15]:
df2 = df.fillna({"Age":df["Age"].mean(),"City":"Unknown","Purchase":df["Purchase"].median()})
df2

  Customer        Age        City  Purchase
0        A  25.000000    New York     200.0
1        B  27.666667  Los Angels     200.0
2        C  30.000000     Unknown     150.0
3        D  27.666667     Chicago     300.0
4        E  28.000000     Unknown     200.0

In [16]:
import warnings
warnings.filterwarnings('ignore')

In [17]:
df_ffill = df.fillna(method = 'ffill')
df_ffill

  Customer   Age        City  Purchase
0        A  25.0    New York     200.0
1        B  25.0  Los Angels     200.0
2        C  30.0  Los Angels     150.0
3        D  30.0     Chicago     300.0
4        E  28.0     Chicago     300.0

In [30]:
df_bfill = df.fillna(method = 'bfill')
df_bfill

  Customer   Age        City  Purchase
0        A  25.0    New York     200.0
1        B  30.0  Los Angels     150.0
2        C  30.0     Chicago     150.0
3        D  28.0     Chicago     300.0
4        E  28.0        None       NaN

In [31]:
df

  Customer   Age        City  Purchase
0        A  25.0    New York     200.0
1        B   NaN  Los Angels       NaN
2        C  30.0        None     150.0
3        D   NaN     Chicago     300.0
4        E  28.0        None       NaN

In [33]:
# dropna()
# By default it will delete recored (axis - 0)
df3 = df.dropna()
df3

  Customer   Age      City  Purchase
0        A  25.0  New York     200.0

In [34]:
df4 = df.dropna(axis = 1)
df4

  Customer
0        A
1        B
2        C
3        D
4        E

In [37]:
# threshold ----> keep rows with atleast 3 non missing values

df5  = df.dropna(thresh = 3)
df5

  Customer   Age      City  Purchase
0        A  25.0  New York     200.0
2        C  30.0      None     150.0
3        D   NaN   Chicago     300.0

In [38]:
df6 = df.dropna(subset = ["Age","Purchase"])
df6

  Customer   Age      City  Purchase
0        A  25.0  New York     200.0
2        C  30.0      None     150.0