## Loading dataset

In [26]:
import pandas as pd
import numpy as np

In [ ]:
# pip install openpyxl ---> to open xl file

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [6]:
df = pd.read_csv('EmployeeData.csv')
df

    EID       FullName Department  Age Gender  AnnualSalary  Bonus%
0   101     John Smith         HR   29      M         50000       5
1   102  Alice Johnson    Finance   35      F         65000       7
2   103    Michael Lee         IT   40      M         80000      10
3   104      Sara Khan  Marketing   28      F         48000       4
4   105   David Miller    Finance   50      M         90000      12
5   106     Emma Brown         IT   32      F         72000       8
6   107   James Wilson         HR   45      M         55000       6
7   108   Sophia Davis      Sales   30      F         60000       5
8   109  Daniel Taylor      Sales   38      M         58000       6
9   110  Olivia Harris  Marketing   27      F         47000       3
10  111    Ethan Clark    Finance   41      M         75000       9
11  112     Ava Martin         HR   36      F         52000       4
12  113  William Lewis         IT   42      M         82000      11
13  114     Mia Walker      Sales   31      F         59000       5
14  115  Benjamin Hall    Finance   39      M         87000      10

In [35]:
df1 = pd.read_excel('Employee Sample Data.xlsx')
df1.head()

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,NaT
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,NaT
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,NaT
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,NaT

In [40]:
df = pd.read_csv("D:\\EmployeeData.csv")
df.head()

   EID       FullName Department  Age Gender  AnnualSalary  Bonus%
0  101     John Smith         HR   29      M         50000       5
1  102  Alice Johnson    Finance   35      F         65000       7
2  103    Michael Lee         IT   40      M         80000      10
3  104      Sara Khan  Marketing   28      F         48000       4
4  105   David Miller    Finance   50      M         90000      12

In [41]:
df.tail()

    EID       FullName Department  Age Gender  AnnualSalary  Bonus%
10  111    Ethan Clark    Finance   41      M         75000       9
11  112     Ava Martin         HR   36      F         52000       4
12  113  William Lewis         IT   42      M         82000      11
13  114     Mia Walker      Sales   31      F         59000       5
14  115  Benjamin Hall    Finance   39      M         87000      10

In [42]:
df.shape

(15, 7)

In [43]:
df.columns

Index(['EID', 'FullName', 'Department', 'Age', 'Gender', 'AnnualSalary',
       'Bonus%'],
      dtype='object')

In [45]:
df.dtypes

EID              int64
FullName        object
Department      object
Age              int64
Gender          object
AnnualSalary     int64
Bonus%           int64
dtype: object

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   EID           15 non-null     int64
 1   FullName      15 non-null     object
 2   Department    15 non-null     object
 3   Age           15 non-null     int64
 4   Gender        15 non-null     object
 5   AnnualSalary  15 non-null     int64
 6   Bonus%        15 non-null     int64
dtypes: int64(4), object(3)
memory usage: 972.0+ bytes

In [49]:
df.describe(include = 'all')

,EID,FullName,Department,Age,Gender,AnnualSalary,Bonus%
count,15.000000,15,15,15.000000,15,15.000000,15.000000
unique,NaN,15,5,NaN,2,NaN,NaN
top,NaN,John Smith,Finance,NaN,M,NaN,NaN
freq,NaN,1,4,NaN,8,NaN,NaN
mean,108.000000,NaN,NaN,36.200000,NaN,65333.333333,7.000000
std,4.472136,NaN,NaN,6.752777,NaN,14607.564903,2.828427
min,101.000000,NaN,NaN,27.000000,NaN,47000.000000,3.000000
25%,104.500000,NaN,NaN,30.500000,NaN,53500.000000,5.000000
50%,108.000000,NaN,NaN,36.000000,NaN,60000.000000,6.000000
75%,111.500000,NaN,NaN,40.500000,NaN,77500.000000,9.500000
max,115.000000,NaN,NaN,50.000000,NaN,90000.000000,12.000000

In [50]:
df.head()

   EID       FullName Department  Age Gender  AnnualSalary  Bonus%
0  101     John Smith         HR   29      M         50000       5
1  102  Alice Johnson    Finance   35      F         65000       7
2  103    Michael Lee         IT   40      M         80000      10
3  104      Sara Khan  Marketing   28      F         48000       4
4  105   David Miller    Finance   50      M         90000      12

## Non indexing attributes

In [64]:
print("Shape:" ,df.shape)
print("Size of elements",df.size)
print("Dimensions:" , df.ndim)
print("Column Names:" , df.columns)
print("\nRow index:" , df.index)
print("Data Types:\n" , df.dtypes)
print(" Is DataFrame Empty:", df.empty)
print("Axes:\n" , df.axes)
print("Values:", df.values)

Shape: (15, 7)
Size of elements 105
Dimensions: 2
Column Names: Index(['EID', 'FullName', 'Department', 'Age', 'Gender', 'AnnualSalary',
       'Bonus%'],
      dtype='object')

Row index: RangeIndex(start=0, stop=15, step=1)
Data Types:
 EID              int64
FullName        object
Department      object
Age              int64
Gender          object
AnnualSalary     int64
Bonus%           int64
dtype: object
 Is DataFrame Empty: False
Axes:
 [RangeIndex(start=0, stop=15, step=1), Index(['EID', 'FullName', 'Department', 'Age', 'Gender', 'AnnualSalary',
       'Bonus%'],
      dtype='object')]
Values: [[101 'John Smith' 'HR' 29 'M' 50000 5]
 [102 'Alice Johnson' 'Finance' 35 'F' 65000 7]
 [103 'Michael Lee' 'IT' 40 'M' 80000 10]
 [104 'Sara Khan' 'Marketing' 28 'F' 48000 4]
 [105 'David Miller' 'Finance' 50 'M' 90000 12]
 [106 'Emma Brown' 'IT' 32 'F' 72000 8]
 [107 'James Wilson' 'HR' 45 'M' 55000 6]
 [108 'Sophia Davis' 'Sales' 30 'F' 60000 5]
 [109 'Daniel Taylor' 'Sales' 38 'M' 58000 6]
 [110 'Olivia Harris' 'Marketing' 27 'F' 47000 3]
 [111 'Ethan Clark' 'Finance' 41 'M' 75000 9]
 [112 'Ava Martin' 'HR' 36 'F' 52000 4]
 [113 'William Lewis' 'IT' 42 'M' 82000 11]
 [114 'Mia Walker' 'Sales' 31 'F' 59000 5]
 [115 'Benjamin Hall' 'Finance' 39 'M' 87000 10]]

In [66]:
print("Tranpose:" , df.T)

Tranpose:                       0              1            2          3             4   \
EID                  101            102          103        104           105
FullName      John Smith  Alice Johnson  Michael Lee  Sara Khan  David Miller
Department            HR        Finance           IT  Marketing       Finance
Age                   29             35           40         28            50
Gender                 M              F            M          F             M
AnnualSalary       50000          65000        80000      48000         90000
Bonus%                 5              7           10          4            12

                      5             6             7              8   \
EID                  106           107           108            109
FullName      Emma Brown  James Wilson  Sophia Davis  Daniel Taylor
Department            IT            HR         Sales          Sales
Age                   32            45            30             38
Gender                 F             M             F              M
AnnualSalary       72000         55000         60000          58000
Bonus%                 8             6             5              6

                         9            10          11             12  \
EID                     110          111         112            113
FullName      Olivia Harris  Ethan Clark  Ava Martin  William Lewis
Department        Marketing      Finance          HR             IT
Age                      27           41          36             42
Gender                    F            M           F              M
AnnualSalary          47000        75000       52000          82000
Bonus%                    3            9           4             11

                      13             14
EID                  114            115
FullName      Mia Walker  Benjamin Hall
Department         Sales        Finance
Age                   31             39
Gender                 F              M
AnnualSalary       59000          87000
Bonus%                 5             10

## Utiity methods

In [67]:
df.head()

   EID       FullName Department  Age Gender  AnnualSalary  Bonus%
0  101     John Smith         HR   29      M         50000       5
1  102  Alice Johnson    Finance   35      F         65000       7
2  103    Michael Lee         IT   40      M         80000      10
3  104      Sara Khan  Marketing   28      F         48000       4
4  105   David Miller    Finance   50      M         90000      12

In [68]:
df.tail()

    EID       FullName Department  Age Gender  AnnualSalary  Bonus%
10  111    Ethan Clark    Finance   41      M         75000       9
11  112     Ava Martin         HR   36      F         52000       4
12  113  William Lewis         IT   42      M         82000      11
13  114     Mia Walker      Sales   31      F         59000       5
14  115  Benjamin Hall    Finance   39      M         87000      10

In [69]:
df.sample(2) # selects random 2 records

    EID      FullName Department  Age Gender  AnnualSalary  Bonus%
10  111   Ethan Clark    Finance   41      M         75000       9
6   107  James Wilson         HR   45      M         55000       6

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   EID           15 non-null     int64
 1   FullName      15 non-null     object
 2   Department    15 non-null     object
 3   Age           15 non-null     int64
 4   Gender        15 non-null     object
 5   AnnualSalary  15 non-null     int64
 6   Bonus%        15 non-null     int64
dtypes: int64(4), object(3)
memory usage: 972.0+ bytes

In [72]:
df.describe()

              EID        Age  AnnualSalary     Bonus%
count   15.000000  15.000000     15.000000  15.000000
mean   108.000000  36.200000  65333.333333   7.000000
std      4.472136   6.752777  14607.564903   2.828427
min    101.000000  27.000000  47000.000000   3.000000
25%    104.500000  30.500000  53500.000000   5.000000
50%    108.000000  36.000000  60000.000000   6.000000
75%    111.500000  40.500000  77500.000000   9.500000
max    115.000000  50.000000  90000.000000  12.000000

In [73]:
df.describe(include = 'all')

,EID,FullName,Department,Age,Gender,AnnualSalary,Bonus%
count,15.000000,15,15,15.000000,15,15.000000,15.000000
unique,NaN,15,5,NaN,2,NaN,NaN
top,NaN,John Smith,Finance,NaN,M,NaN,NaN
freq,NaN,1,4,NaN,8,NaN,NaN
mean,108.000000,NaN,NaN,36.200000,NaN,65333.333333,7.000000
std,4.472136,NaN,NaN,6.752777,NaN,14607.564903,2.828427
min,101.000000,NaN,NaN,27.000000,NaN,47000.000000,3.000000
25%,104.500000,NaN,NaN,30.500000,NaN,53500.000000,5.000000
50%,108.000000,NaN,NaN,36.000000,NaN,60000.000000,6.000000
75%,111.500000,NaN,NaN,40.500000,NaN,77500.000000,9.500000
max,115.000000,NaN,NaN,50.000000,NaN,90000.000000,12.000000

In [78]:
print(df['Department'].unique())
print(df['Department'].nunique())  # to count of unique departments

['HR' 'Finance' 'IT' 'Marketing' 'Sales']
5

In [79]:
print(df['Gender'].value_counts())

Gender
M    8
F    7
Name: count, dtype: int64

In [82]:
print(df[['FullName' , 'AnnualSalary']])

FullName       AnnualSalary
Alice Johnson  65000           1
Ava Martin     52000           1
Benjamin Hall  87000           1
Daniel Taylor  58000           1
David Miller   90000           1
Emma Brown     72000           1
Ethan Clark    75000           1
James Wilson   55000           1
John Smith     50000           1
Mia Walker     59000           1
Michael Lee    80000           1
Olivia Harris  47000           1
Sara Khan      48000           1
Sophia Davis   60000           1
William Lewis  82000           1
Name: count, dtype: int64

In [83]:
print(df[df['Age'] > 35])

    EID       FullName Department  Age Gender  AnnualSalary  Bonus%
2   103    Michael Lee         IT   40      M         80000      10
4   105   David Miller    Finance   50      M         90000      12
6   107   James Wilson         HR   45      M         55000       6
8   109  Daniel Taylor      Sales   38      M         58000       6
10  111    Ethan Clark    Finance   41      M         75000       9
11  112     Ava Martin         HR   36      F         52000       4
12  113  William Lewis         IT   42      M         82000      11
14  115  Benjamin Hall    Finance   39      M         87000      10

In [86]:
df = df.rename(columns = {"AnnualSalary" : "Salary"})
df

    EID       FullName Department  Age Gender  Salary  Bonus%
0   101     John Smith         HR   29      M   50000       5
1   102  Alice Johnson    Finance   35      F   65000       7
2   103    Michael Lee         IT   40      M   80000      10
3   104      Sara Khan  Marketing   28      F   48000       4
4   105   David Miller    Finance   50      M   90000      12
5   106     Emma Brown         IT   32      F   72000       8
6   107   James Wilson         HR   45      M   55000       6
7   108   Sophia Davis      Sales   30      F   60000       5
8   109  Daniel Taylor      Sales   38      M   58000       6
9   110  Olivia Harris  Marketing   27      F   47000       3
10  111    Ethan Clark    Finance   41      M   75000       9
11  112     Ava Martin         HR   36      F   52000       4
12  113  William Lewis         IT   42      M   82000      11
13  114     Mia Walker      Sales   31      F   59000       5
14  115  Benjamin Hall    Finance   39      M   87000      10

In [88]:
df_indexed = df.set_index('EID')
df_indexed.head()

          FullName Department  Age Gender  Salary  Bonus%
EID
101     John Smith         HR   29      M   50000       5
102  Alice Johnson    Finance   35      F   65000       7
103    Michael Lee         IT   40      M   80000      10
104      Sara Khan  Marketing   28      F   48000       4
105   David Miller    Finance   50      M   90000      12

In [89]:
#sort_values() ----> sort rows by column values
#sort_values()-----> sort rows by index

In [90]:
sorted_df = df.sort_values(by = 'Salary' , ascending  = False)  # single columns
sorted_df.head()

    EID       FullName Department  Age Gender  Salary  Bonus%
4   105   David Miller    Finance   50      M   90000      12
14  115  Benjamin Hall    Finance   39      M   87000      10
12  113  William Lewis         IT   42      M   82000      11
2   103    Michael Lee         IT   40      M   80000      10
10  111    Ethan Clark    Finance   41      M   75000       9

In [91]:
sort_multi = df.sort_values(by = ['Department' , 'Age'], ascending = [True , False])
sort_multi.head()

    EID       FullName Department  Age Gender  Salary  Bonus%
4   105   David Miller    Finance   50      M   90000      12
10  111    Ethan Clark    Finance   41      M   75000       9
14  115  Benjamin Hall    Finance   39      M   87000      10
1   102  Alice Johnson    Finance   35      F   65000       7
6   107   James Wilson         HR   45      M   55000       6

In [94]:
# rank()  ---> Assign rank to each column
df["SalaryRank"] = df["Salary"].rank(ascending = False)
print(df[['FullName' , 'Salary' , 'SalaryRank']])

         FullName  Salary  SalaryRank
0      John Smith   50000        13.0
1   Alice Johnson   65000         7.0
2     Michael Lee   80000         4.0
3       Sara Khan   48000        14.0
4    David Miller   90000         1.0
5      Emma Brown   72000         6.0
6    James Wilson   55000        11.0
7    Sophia Davis   60000         8.0
8   Daniel Taylor   58000        10.0
9   Olivia Harris   47000        15.0
10    Ethan Clark   75000         5.0
11     Ava Martin   52000        12.0
12  William Lewis   82000         3.0
13     Mia Walker   59000         9.0
14  Benjamin Hall   87000         2.0

## DataFrame iteration Methods

## itertows()

In [98]:
data = {
    "ID":[1,2,3],
    "Name":["A" , "B" , "C"],
    "Marks":[85,90,75]
}
df = pd.DataFrame(data)

for index , row in df.iterrows():
    print(f"Index: {index}, ID: {row["ID"]}, Name: {row["Name"]} , Marks:{row["Marks"]}")

Index: 0, ID: 1, Name: A , Marks:85
Index: 1, ID: 2, Name: B , Marks:90
Index: 2, ID: 3, Name: C , Marks:75

## itertuples()

In [101]:
data = {
    "ID":[1,2,3],
    "Name":["A" , "B" , "C"],
    "Marks":[85,90,75]
}
df = pd.DataFrame(data)

for  row in df.itertuples():
    print(f"Index: {index}, ID: {row.ID}, Name: {row.Name} , Marks:{row.Marks}")

Index: 2, ID: 1, Name: A , Marks:85
Index: 2, ID: 2, Name: B , Marks:90
Index: 2, ID: 3, Name: C , Marks:75

## item()

In [102]:
#iterate over columns of a DataFrame
#for each column it returns (column_name , Series) pair
data = {
    "ID":[1,2,3],
    "Name":["A" , "B" , "C"],
    "Marks":[85,90,75]
}
df = pd.DataFrame(data)

for col_name, col_data in df.items():
    print(f"Column Name:,{col_name}")
    print(col_data)
    print("-----------------")

Column Name:,ID
0    1
1    2
2    3
Name: ID, dtype: int64
-----------------
Column Name:,Name
0    A
1    B
2    C
Name: Name, dtype: object
-----------------
Column Name:,Marks
0    85
1    90
2    75
Name: Marks, dtype: int64
-----------------