In [83]:
import pandas as pd
import numpy as np

In [6]:
# Create a series from dictionary
#Keys ---> index
#values ---> data

data = {"A":85 , "B":92 , "C":78 , "D":90, "E":88}
marks = pd.Series(data)
print(marks)

A    85
B    92
C    78
D    90
E    88
dtype: int64

In [11]:
#Sort a series

data = {"A":85 , "D":90 , "C":78 ,"B":92 , "E":88}
marks = pd.Series(data)
print(marks)
print("-" * 20)
#Sort by index
print(marks.sort_index())
print("-" * 20)
# Sort by values
print(marks.sort_values()) # ascending

print(marks.sort_values(ascending = False))

A    85
D    90
C    78
B    92
E    88
dtype: int64
--------------------
A    85
B    92
C    78
D    90
E    88
dtype: int64
--------------------
C    78
A    85
E    88
D    90
B    92
dtype: int64
B    92
D    90
E    88
A    85
C    78
dtype: int64

In [13]:
# Reordering index in series
data = {"A":85 , "D":90 , "C":78 ,"B":92 , "E":88}
marks = pd.Series(data)
print(marks)
print("-" * 30)

marks = pd.Series(data,index = ["A","B","C","D","E"])
print(marks)

A    85
D    90
C    78
B    92
E    88
dtype: int64
------------------------------
A    85
B    92
C    78
D    90
E    88
dtype: int64

## DataFrame

In [14]:
data = {
    'Name':["A","B","C","D"],
    'Age':[20,21,19,22],
    'Marks':[85,92,78,90]
}

df = pd.DataFrame(data)
df

  Name  Age  Marks
0    A   20     85
1    B   21     92
2    C   19     78
3    D   22     90

In [16]:
print(df.index)
print(df.columns)
print(df.shape)

RangeIndex(start=0, stop=4, step=1)
Index(['Name', 'Age', 'Marks'], dtype='object')
(4, 3)

In [19]:
data = [
    ["A",23,92],
    ["B",24,93],
    ["C",21,78]
]
df = pd.DataFrame(data , columns = ['Name' , 'Age' , 'Marks'])
df

  Name  Age  Marks
0    A   23     92
1    B   24     93
2    C   21     78

In [21]:
# Create DataFrame from dictionary of series

data = {
    'Maths':pd.Series([85,92,78],index = ['A' , 'B', 'C']),
    'Science':pd.Series([88,91,75],index = ['A','B','C'])
}
df = pd.DataFrame(data)
df

   Maths  Science
A     85       88
B     92       91
C     78       75

In [33]:
data = {
    'Name':["A","B","C","D"],
    'Age':[20,21,19,22],
    'Marks':[85,92,78,90]
}
df = pd.DataFrame(data , index = ['s1','s2','s3','s4'])
df

   Name  Age  Marks
s1    A   20     85
s2    B   21     92
s3    C   19     78
s4    D   22     90

## loc and iloc

In [37]:
data = pd.Series(['a' , 'b' , 'c' , 'd'], index = [101,102,103,104])
print(data)
print("-----------------------")
print('loc values') # manually generated index values
print(data.loc[101])
print(data.loc[102])
print(data.loc[103])
print(data.loc[104])

#iloc
print('iloc values') # original index values
print(data.iloc[0])
print(data.iloc[1])
print(data.iloc[2])
print(data.iloc[3])
print("------------------------------")
print(data.loc[102:104])
print("------------------------------")
print(data.iloc[1:4])

101    a
102    b
103    c
104    d
dtype: object
-----------------------
loc values
a
b
c
d
iloc values
a
b
c
d
------------------------------
102    b
103    c
104    d
dtype: object
------------------------------
102    b
103    c
104    d
dtype: object

In [64]:
data = {
    'Name':['A' , 'B' , 'C' , 'D' , 'E'],
    "Age":[23,25,22,24,26],
    "Dept":['HR' , 'IT' , 'FINANCE', 'IT' , 'HR'],
    "Salary":[30000,35000,28000,40000,45000]
}

df = pd.DataFrame(data, index = ['E1' ,'E2' ,'E3', 'E4','E5'])
print(df.loc['E1'])
print("----------------------------")
print(df.loc['E2'])
print("----------------------------")
print(df.loc[['E1' , 'E3']])
print("----------------------------")
print(df.loc['E2' : 'E4'])
print("----------------------------")
print(df.loc[['E2' ,'E3', 'E4'] , ['Name' , 'Salary']])
print("----------------------------")
print(df.loc[df['Salary'] > 35000])
print('iloc examples')
print("----------------------------")
print(df.iloc[0])
print("----------------------------")
print(df.iloc[[0,3]])
print("----------------------------")
print(df.iloc[0:4])
print("----------------------------")
print(df.iloc[[0,2],[0,3]]) #0,2 ---> e1,e3rows, ----> name,salary(coloumns)
print("----------------------------")
high_salary = df['Salary'] > 35000
print(df.iloc[high_salary.values])

Name          A
Age          23
Dept         HR
Salary    30000
Name: E1, dtype: object
----------------------------
Name          B
Age          25
Dept         IT
Salary    35000
Name: E2, dtype: object
----------------------------
   Name  Age     Dept  Salary
E1    A   23       HR   30000
E3    C   22  FINANCE   28000
----------------------------
   Name  Age     Dept  Salary
E2    B   25       IT   35000
E3    C   22  FINANCE   28000
E4    D   24       IT   40000
----------------------------
   Name  Salary
E2    B   35000
E3    C   28000
E4    D   40000
----------------------------
   Name  Age Dept  Salary
E4    D   24   IT   40000
E5    E   26   HR   45000
iloc examples
----------------------------
Name          A
Age          23
Dept         HR
Salary    30000
Name: E1, dtype: object
----------------------------
   Name  Age Dept  Salary
E1    A   23   HR   30000
E4    D   24   IT   40000
----------------------------
   Name  Age     Dept  Salary
E1    A   23       HR   30000
E2    B   25       IT   35000
E3    C   22  FINANCE   28000
E4    D   24       IT   40000
----------------------------
   Name  Salary
E1    A   30000
E3    C   28000
----------------------------
   Name  Age Dept  Salary
E4    D   24   IT   40000
E5    E   26   HR   45000

## DataFrame Operations: Column & row Manipulation

In [66]:
data = {
    'Name':["A","B","C","D","E"],
    'Age':[20,21,19,22,26],
    'Marks':[85,92,78,90,88],
    'City':["Delhi","Mumbai","Chennai" ,"Banglore" ,"Hyderabad"]
}
df = pd.DataFrame(data)
df

  Name  Age  Marks       City
0    A   20     85      Delhi
1    B   21     92     Mumbai
2    C   19     78    Chennai
3    D   22     90   Banglore
4    E   26     88  Hyderabad

In [71]:
# column selection

print(df['Name'])
print("--------------------------")
print(df[['Name' , 'Marks']])

0    A
1    B
2    C
3    D
4    E
Name: Name, dtype: object
--------------------------
  Name  Marks
0    A     85
1    B     92
2    C     78
3    D     90
4    E     88

In [72]:
# Add new Column
df['Grade'] = ["B", "A","C","A+","B+"]
df

  Name  Age  Marks       City Grade
0    A   20     85      Delhi     B
1    B   21     92     Mumbai     A
2    C   19     78    Chennai     C
3    D   22     90   Banglore    A+
4    E   26     88  Hyderabad    B+

In [76]:
#sorting
print(df.sort_values(by = 'Age'))  #ascending
print("------------------------------")
print(df.sort_values(by = 'Age' , ascending = False))

  Name  Age  Marks       City Grade
2    C   19     78    Chennai     C
0    A   20     85      Delhi     B
1    B   21     92     Mumbai     A
3    D   22     90   Banglore    A+
4    E   26     88  Hyderabad    B+
------------------------------
  Name  Age  Marks       City Grade
4    E   26     88  Hyderabad    B+
3    D   22     90   Banglore    A+
1    B   21     92     Mumbai     A
0    A   20     85      Delhi     B
2    C   19     78    Chennai     C

In [77]:
# column deletion

df  = df.drop("City" , axis = 1)
df

  Name  Age  Marks Grade
0    A   20     85     B
1    B   21     92     A
2    C   19     78     C
3    D   22     90    A+
4    E   26     88    B+

In [78]:
#Row selection
print(df.iloc[2])
print("-------------------------")
print(df.loc[2])

Name      C
Age      19
Marks    78
Grade     C
Name: 2, dtype: object
-------------------------
Name      C
Age      19
Marks    78
Grade     C
Name: 2, dtype: object

In [79]:
# Add new Row
new_row = {
    "Name":"F" ,"Age":23,"Marks":92,"Grade":"A"
}
df.loc[5] = new_row
print(df)

  Name  Age  Marks Grade
0    A   20     85     B
1    B   21     92     A
2    C   19     78     C
3    D   22     90    A+
4    E   26     88    B+
5    F   23     92     A

In [80]:
#Row deletion
df = df.drop(5,axis = 0)
df

  Name  Age  Marks Grade
0    A   20     85     B
1    B   21     92     A
2    C   19     78     C
3    D   22     90    A+
4    E   26     88    B+

In [82]:
# Gives statistical values for numerical columns
df.describe()
print("-------------------------------")
print(df.describe(include = 'all'))  # for all columns

-------------------------------
       Name        Age      Marks Grade
count     5   5.000000   5.000000     5
unique    5        NaN        NaN     5
top       A        NaN        NaN     B
freq      1        NaN        NaN     1
mean    NaN  21.600000  86.600000   NaN
std     NaN   2.701851   5.458938   NaN
min     NaN  19.000000  78.000000   NaN
25%     NaN  20.000000  85.000000   NaN
50%     NaN  21.000000  88.000000   NaN
75%     NaN  22.000000  90.000000   NaN
max     NaN  26.000000  92.000000   NaN

In [84]:
# groupby()
data = {
    'Name':["A","B","C","D","E"],
    'Age':[25,25,24,24,25],
    'Marks':[85,92,78,90,88],
    'City':["Delhi","Mumbai","Chennai" ,"Banglore" ,"Hyderabad"]
}
df = pd.DataFrame(data)
df

  Name  Age  Marks       City
0    A   25     85      Delhi
1    B   25     92     Mumbai
2    C   24     78    Chennai
3    D   24     90   Banglore
4    E   25     88  Hyderabad

In [85]:
df.groupby("Age")["Marks"].mean()

Age
24    84.000000
25    88.333333
Name: Marks, dtype: float64