## Data Type Conversion

### astype()

In [1]:
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
df = pd.DataFrame({
    "Age":["23" , "25" , "21"],
    "Salary":[1000.5, 2000.0, 1500.75],
    "Employed":[1,0,1]
})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Age       3 non-null      object
 1   Salary    3 non-null      float64
 2   Employed  3 non-null      int64
dtypes: float64(1), int64(1), object(1)
memory usage: 204.0+ bytes

In [8]:
# Convert age from object to int
df["Age"] = df["Age"].astype(int)
df.dtypes

Age           int64
Salary      float64
Employed      int64
dtype: object

In [10]:
#Convert Salary from float to int
df["Salary"] = df["Salary"].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Age       3 non-null      int64
 1   Salary    3 non-null      int64
 2   Employed  3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes

In [12]:
df["Employed"] = df["Employed"].astype(bool)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Age       3 non-null      int64
 1   Salary    3 non-null      int64
 2   Employed  3 non-null      bool
dtypes: bool(1), int64(2)
memory usage: 183.0 bytes

### pd.to_numeric

In [18]:
df["Age"] = df["Age"].astype(str)
df.dtypes
df["Age"] = pd.to_numeric(df["Age"] , errors = "coerce")
print(df.dtypes)

Age         int64
Salary      int64
Employed     bool
dtype: object

### pd.to_datetime

In [22]:
df["JoinDate"] = pd.to_datetime(['2025-09-09','2024-01-01','2023-12-15'])
df.dtypes

Age                  int64
Salary               int64
Employed              bool
JoinDate    datetime64[ns]
dtype: object

### pd.to_timedelta

In [24]:
df["Experience"] = pd.to_timedelta(["365 days" , "730 days", "1095 days"])
df.dtypes

Age                     int64
Salary                  int64
Employed                 bool
JoinDate       datetime64[ns]
Experience    timedelta64[ns]
dtype: object

In [27]:
df["Department"] = pd.Series(["HR" , "IT", "Finance"]).astype("category")
df.dtypes
df

   Age  Salary  Employed   JoinDate Experience Department
0   23    1000      True 2025-09-09   365 days         HR
1   25    2000     False 2024-01-01   730 days         IT
2   21    1500      True 2023-12-15  1095 days    Finance

## Row Label/index

In [32]:
df = pd.DataFrame({
    "Name":["A","B","C"],
    "Marks":[85,90,78]
},index = [101,102,103])
print(df.index)
print(df.index.tolist())

Index([101, 102, 103], dtype='int64')
[101, 102, 103]

In [35]:
print(df.reset_index()) # keeps old index as column
print(df.reset_index(drop = True)) # removes old index column

   index Name  Marks
0    101    A     85
1    102    B     90
2    103    C     78
  Name  Marks
0    A     85
1    B     90
2    C     78

    Name  Marks
101    A     85
102    B     90
103    C     78

In [41]:
df = pd.DataFrame({
    "Roll No":[101,102,103],
    "Name":["A","B","C"],
    "Marks":[85,90,78]
})
df2 = df.set_index("Roll No")
df2

        Name  Marks
Roll No
101        A     85
102        B     90
103        C     78

In [42]:
df2.loc[102]

Name      B
Marks    90
Name: 102, dtype: object

In [46]:
df.iloc[2]

Roll No    103
Name         C
Marks       78
Name: 2, dtype: object

In [49]:
df = pd.DataFrame({
    "Name":["A","B","C"],
    "Marks":[85,90,78]
},index = [101,102,103])
df

    Name  Marks
101    A     85
102    B     90
103    C     78

In [52]:
# Rename
df_renamed = df.rename(index = {101:201 , 103:203})
df_renamed

    Name  Marks
201    A     85
102    B     90
203    C     78

## Adding rows and Dropping rows

In [53]:
# use loc and iloc
# use concat
# to add at end use loc or conacat
df = pd.DataFrame({
    "Name":["A","B","C"],
    "Marks":[85,90,78]
},index = [101,102,103])
df

    Name  Marks
101    A     85
102    B     90
103    C     78

In [59]:
df.loc[104] = ["D" ,85] 
df

    Name  Marks
101    A     85
102    B     90
103    C     78
104    D     85

In [62]:
#concat
new_row = pd.DataFrame({"Name":["E"] , "Marks":[95]} , index = [105])
df2 = pd.concat([df, new_row])
df2

    Name  Marks
101    A     85
102    B     90
103    C     78
104    D     85
105    E     95

In [64]:
df = pd.DataFrame({
    "Name":["A","B","C"],
    "Marks":[85,90,78]
},index = [101,102,103])
df

    Name  Marks
101    A     85
102    B     90
103    C     78

In [66]:
# insert new record in second place
new_row = pd.DataFrame({"Name":["D"] , "Marks":[95]} , index = [102])
df2 = pd.concat([df,new_row])
df2 = df2.sort_index().reset_index(drop = True)
df2

  Name  Marks
0    A     85
1    B     90
2    D     95
3    C     78

In [68]:
#Insert new record in first place 
new_row = pd.DataFrame({"Name":["D"] , "Marks":[95]} , index = [100])
df2 = pd.concat([df,new_row])
df2 = df2.sort_index().reset_index(drop = True)
df2

  Name  Marks
0    D     95
1    A     85
2    B     90
3    C     78

## Droppping rows

In [89]:
df = pd.DataFrame({
    "Name":["A","B","C","D"],
    "Marks":[85,90,78,90]
},index = [101,102,103,104])
df

    Name  Marks
101    A     85
102    B     90
103    C     78
104    D     90

In [90]:
df1 = df.drop(102)
df1

    Name  Marks
101    A     85
103    C     78
104    D     90

In [91]:
df2 = df.drop([102,104])
df2

    Name  Marks
101    A     85
103    C     78

In [92]:
df.drop([102,104], inplace  = True)
df

    Name  Marks
101    A     85
103    C     78

## Boolean Row Selction by vlaues

In [94]:
data = ({
    "Name":["A","B","C","D","E","F"],
    "Age":[25,30,35,40,45,50],
    "City":["New york" , "Paris","London","Berlin" ,"Paris" , "London"],
    "Salary":[50000,60000,70000,80000,90000,100000]
})
df = pd.DataFrame(data)
df

  Name  Age      City  Salary
0    A   25  New york   50000
1    B   30     Paris   60000
2    C   35    London   70000
3    D   40    Berlin   80000
4    E   45     Paris   90000
5    F   50    London  100000

In [97]:
df[df["Age"] == 30]

  Name  Age   City  Salary
1    B   30  Paris   60000

In [99]:
df[df["City"] != 'Paris']

  Name  Age      City  Salary
0    A   25  New york   50000
2    C   35    London   70000
3    D   40    Berlin   80000
5    F   50    London  100000

In [100]:
df[df["Age"] >= 40]

  Name  Age    City  Salary
3    D   40  Berlin   80000
4    E   45   Paris   90000
5    F   50  London  100000

In [101]:
df[df["Age"] <= 40]

  Name  Age      City  Salary
0    A   25  New york   50000
1    B   30     Paris   60000
2    C   35    London   70000
3    D   40    Berlin   80000

In [102]:
# AND condition (&)

df[(df["Age"] > 30 )& (df["City"] == "Paris")]

  Name  Age   City  Salary
4    E   45  Paris   90000

In [104]:
# OR Condition (|)
df[(df["City"] == "Paris" )| (df["Age"] < 30)]

  Name  Age      City  Salary
0    A   25  New york   50000
1    B   30     Paris   60000
4    E   45     Paris   90000

In [106]:
# isin() condition
df[df["City"].isin(["Paris","Hyderabad"])]

  Name  Age   City  Salary
1    B   30  Paris   60000
4    E   45  Paris   90000

In [108]:
# not in (~ with isin())
df[~df["City"].isin(["Paris","Hyderabad"])]  #give other than paris and hyderabad

  Name  Age      City  Salary
0    A   25  New york   50000
2    C   35    London   70000
3    D   40    Berlin   80000
5    F   50    London  100000

In [110]:
# str.contains
df[df["City"].str.contains("on")]

  Name  Age    City  Salary
2    C   35  London   70000
5    F   50  London  100000

In [111]:
# str.notcontains
df[~df["City"].str.contains("on")]

  Name  Age      City  Salary
0    A   25  New york   50000
1    B   30     Paris   60000
3    D   40    Berlin   80000
4    E   45     Paris   90000

In [112]:
#Between condition
df[df["Age"].between(30,45)]

  Name  Age    City  Salary
1    B   30   Paris   60000
2    C   35  London   70000
3    D   40  Berlin   80000
4    E   45   Paris   90000

In [113]:
# NotBetween condition
df[~df["Age"].between(30,45)]

  Name  Age      City  Salary
0    A   25  New york   50000
5    F   50    London  100000

In [114]:
# StartsWith
df[df["City"].str.startswith("N")]

  Name  Age      City  Salary
0    A   25  New york   50000

In [117]:
# Not StartsWith
df[~df["City"].str.startswith("N")]

  Name  Age    City  Salary
1    B   30   Paris   60000
2    C   35  London   70000
3    D   40  Berlin   80000
4    E   45   Paris   90000
5    F   50  London  100000

In [119]:
# Endswith()
df[df["City"].str.endswith("n")]

  Name  Age    City  Salary
2    C   35  London   70000
3    D   40  Berlin   80000
5    F   50  London  100000

In [120]:
# NOT Endswith()
df[~df["City"].str.endswith("n")]

  Name  Age      City  Salary
0    A   25  New york   50000
1    B   30     Paris   60000
4    E   45     Paris   90000

In [121]:
# age>30, city = london , salary>=7000
df[(df["Age"]>30) & (df["City"] == "London") & (df["Salary"] > 70000)]

  Name  Age    City  Salary
5    F   50  London  100000