In [2]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [3]:
data = {
    "Maths":[90,80,70],
    "Science":[85,95,75],
    "English":[88,76,92]
}

df = pd.DataFrame(data)
df

   Maths  Science  English
0     90       85       88
1     80       95       76
2     70       75       92

In [6]:
#Sum ----> df.sum()

print(df.sum()) #column wise
print("------------------------")
print(df.sum(axis = 1)) #row wise

Maths      240
Science    255
English    256
dtype: int64
------------------------
0    263
1    251
2    237
dtype: int64

In [7]:
#Mean---> df.mean()
print(df.mean())

Maths      80.000000
Science    85.000000
English    85.333333
dtype: float64

In [8]:
#Median
print(df.median())

Maths      80.0
Science    85.0
English    88.0
dtype: float64

In [10]:
# min() , max()
print(df.min())
print("-----------------")
print(df.max())

Maths      70
Science    75
English    76
dtype: int64
Maths      90
Science    95
English    92
dtype: int64

In [11]:
# Variance()
print(df.var())

Maths      100.000000
Science    100.000000
English     69.333333
dtype: float64

In [13]:
#Standard deviaton
print(df.std())

Maths      10.000000
Science    10.000000
English     8.326664
dtype: float64

In [14]:
# Cumilative sum
print(df.cumsum())

   Maths  Science  English
0     90       85       88
1    170      180      164
2    240      255      256

In [15]:
#Cumulative product
print(df.cumprod())

    Maths  Science  English
0      90       85       88
1    7200     8075     6688
2  504000   605625   615296

In [16]:
# Absolute value ----> Turns negative value to positve values
print(df.abs())

   Maths  Science  English
0     90       85       88
1     80       95       76
2     70       75       92

In [17]:
# Power -----> Returns all square values
print(df.pow(2))

   Maths  Science  English
0   8100     7225     7744
1   6400     9025     5776
2   4900     5625     8464

In [18]:
#Round()
print(df.round())

   Maths  Science  English
0     90       85       88
1     80       95       76
2     70       75       92

In [21]:
# count ---> Returns the no of non NA values in each column
print(df.count())

Maths      3
Science    3
English    3
dtype: int64

In [22]:
# Product 
print(df.prod())

Maths      504000
Science    605625
English    615296
dtype: int64

In [23]:
# Mode---> Returns the most frequennt value in the datasfram
print(df.mode())

   Maths  Science  English
0     70       75       76
1     80       85       88
2     90       95       92

In [24]:
# Correlation
#values Range ---> -1 to +1

print(df.corr())

            Maths   Science   English
Maths    1.000000  0.500000 -0.240192
Science  0.500000  1.000000 -0.960769
English -0.240192 -0.960769  1.000000

In [25]:
# Covariance
print(df.cov())

         Maths  Science    English
Maths    100.0     50.0 -20.000000
Science   50.0    100.0 -80.000000
English  -20.0    -80.0  69.333333

## Column labels/index

In [8]:
df = pd.DataFrame({
    "Name":["A","B","C"],
    "Age":[23,25,21],
    "City":["Delhi" , "Mumbai" , "Chennai"]
})
df

  Name  Age     City
0    A   23    Delhi
1    B   25   Mumbai
2    C   21  Chennai

In [29]:
df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [30]:
print(df.columns[0])

Name

In [32]:
print(list(df.columns))

['Name', 'Age', 'City']

In [34]:
print(df.keys())

Index(['Name', 'Age', 'City'], dtype='object')

In [38]:
df["Name"]

0    A
1    B
2    C
Name: Name, dtype: object

In [40]:
print(df.index)

RangeIndex(start=0, stop=3, step=1)

In [41]:
print(list(df.index))

[0, 1, 2]

In [42]:
print(df.index[0])

0

In [44]:
df = pd.DataFrame({
    "Name":["A","B","C"],
    "Age":[23,25,21],
    "City":["Delhi" , "Mumbai" , "Chennai"]
},index = ['emp1', 'emp2', 'emp3'])
df

     Name  Age     City
emp1    A   23    Delhi
emp2    B   25   Mumbai
emp3    C   21  Chennai

In [46]:
df.index[0]

'emp1'

In [9]:
# Rename column label
df = pd.DataFrame({
    "Name":["A","B","C"],
    "Age":[23,25,21],
    "City":["Delhi" , "Mumbai" , "Chennai"]
})
df

  Name  Age     City
0    A   23    Delhi
1    B   25   Mumbai
2    C   21  Chennai

In [50]:
df1 = df.rename( columns = {"Name":"FullName" , "City":"Location"})
df1

  FullName  Age Location
0        A   23    Delhi
1        B   25   Mumbai
2        C   21  Chennai

In [10]:
df2 = df.copy()
df2.columns = ["FullName" , "Years" , "Location"]
df2

  FullName  Years Location
0        A     23    Delhi
1        B     25   Mumbai
2        C     21  Chennai

In [11]:
df2.columns = [i.upper() for i in df2.columns]
df2

  FULLNAME  YEARS LOCATION
0        A     23    Delhi
1        B     25   Mumbai
2        C     21  Chennai

In [12]:
df3 = df2.add_prefix('emp_')
df3

  emp_FULLNAME  emp_YEARS emp_LOCATION
0            A         23        Delhi
1            B         25       Mumbai
2            C         21      Chennai

In [14]:
df4 = df2.add_suffix('_data')
df4

  FULLNAME_data  YEARS_data LOCATION_data
0             A          23         Delhi
1             B          25        Mumbai
2             C          21       Chennai

In [15]:
df5= df.set_axis(["FullName" , "Years", "Location"] , axis  = 1)

df5

  FullName  Years Location
0        A     23    Delhi
1        B     25   Mumbai
2        C     21  Chennai

In [31]:
df5.columns = df5.columns.str.upper()
df5

  FULLNAME  YEARS LOCATION
0        A     23    Delhi
1        B     25   Mumbai
2        C     21  Chennai

### Selecting and Swapping columns

In [32]:
df = pd.DataFrame({
    "Name":["A","B","C"],
    "Age":[23,25,21],
    "City":["Delhi" , "Mumbai" , "Chennai"]
})
df

  Name  Age     City
0    A   23    Delhi
1    B   25   Mumbai
2    C   21  Chennai

In [41]:
print(df["Name"])
print("---------------------")
print(df[["Name" , "City"]])
print("-----------------------")
print(df.iloc[:,0]) # first column
print("------------------------")
print(df.iloc[:,[0,2]])
print("-------------------------")
print(df.iloc[:,0:2])

0    A
1    B
2    C
Name: Name, dtype: object
---------------------
  Name     City
0    A    Delhi
1    B   Mumbai
2    C  Chennai
-----------------------
0    A
1    B
2    C
Name: Name, dtype: object
------------------------
  Name     City
0    A    Delhi
1    B   Mumbai
2    C  Chennai
-------------------------
  Name  Age
0    A   23
1    B   25
2    C   21

In [54]:
#Swapping
df1 = df[["Name", "Age" , "City"]]
print(df1)
print("------------------------")
#SWap two columns (2nd Method)
cols = list(df.columns)
cols[1] , cols[2]  = cols[2] , cols[1]
df2 = df[cols]
print(df2)
print("------------------------")


#3rd method ---> 
df3 = df.reindex(columns = ["City", "Name" , "Age"])
print(df3)
print("------------------------")
# 4TH method
df4 = df.iloc[:,[2,0,1]]
print(df4)

  Name  Age     City
0    A   23    Delhi
1    B   25   Mumbai
2    C   21  Chennai
------------------------
  Name     City  Age
0    A    Delhi   23
1    B   Mumbai   25
2    C  Chennai   21
------------------------
      City Name  Age
0    Delhi    A   23
1   Mumbai    B   25
2  Chennai    C   21
------------------------
      City Name  Age
0    Delhi    A   23
1   Mumbai    B   25
2  Chennai    C   21

### Addding new column and drop existing column

In [55]:
df = pd.DataFrame({
    "Name":["A","B","C"],
    "Age":[23,25,21],
    "City":["Delhi" , "Mumbai" , "Chennai"]
})
df

  Name  Age     City
0    A   23    Delhi
1    B   25   Mumbai
2    C   21  Chennai

In [56]:
#Add new column
df["Country"] = "India"
df

  Name  Age     City Country
0    A   23    Delhi   India
1    B   25   Mumbai   India
2    C   21  Chennai   India

In [81]:
df["Marks"] = [85,90,94]
df
df["Age_after_5years"] = df["Age"] + 5
df

  Name  Age     City Country  Age_after_5years  Marks
0    A   23    Delhi   India                28     85
1    B   25   Mumbai   India                30     90
2    C   21  Chennai   India                26     94

In [82]:
df = df.assign(Status = ["Pass" , "Pass" , "Pass"])
df

  Name  Age     City Country  Age_after_5years  Marks Status
0    A   23    Delhi   India                28     85   Pass
1    B   25   Mumbai   India                30     90   Pass
2    C   21  Chennai   India                26     94   Pass

In [83]:
#Dropping columns
df = df.drop("Marks" , axis = 1)
df

  Name  Age     City Country  Age_after_5years Status
0    A   23    Delhi   India                28   Pass
1    B   25   Mumbai   India                30   Pass
2    C   21  Chennai   India                26   Pass

In [85]:
df.drop("Status" , axis =1 , inplace = True) # inplace modifies the original directly , no need to reassign
df

  Name  Age     City Country  Age_after_5years
0    A   23    Delhi   India                28
1    B   25   Mumbai   India                30
2    C   21  Chennai   India                26

### Vectorized Arthemtic Operations in pandas

In [86]:
df = pd.DataFrame({
    "A":[10,20,30],
    "B":[1,2,3]
})
df

    A  B
0  10  1
1  20  2
2  30  3

In [87]:
df["A + B"] = df["A"] + df["B"]
df

    A  B  A + B
0  10  1     11
1  20  2     22
2  30  3     33

In [88]:
df["A - B"] = df["A"] - df["B"]
df

    A  B  A + B  A - B
0  10  1     11      9
1  20  2     22     18
2  30  3     33     27

In [90]:
df["A * B"] = df["A"] * df["B"]
df

    A  B  A + B  A - B  A * B
0  10  1     11      9     10
1  20  2     22     18     40
2  30  3     33     27     90

In [91]:
df["A / B"] = df["A"] / df["B"]
df

    A  B  A + B  A - B  A * B  A / B
0  10  1     11      9     10   10.0
1  20  2     22     18     40   10.0
2  30  3     33     27     90   10.0

In [92]:
df["A % B"] = df["A"] % df["B"]
df

    A  B  A + B  A - B  A * B  A / B  A % B
0  10  1     11      9     10   10.0      0
1  20  2     22     18     40   10.0      0
2  30  3     33     27     90   10.0      0

In [93]:
df["A ** B"] = df["A"] ** df["B"]
df

    A  B  A + B  A - B  A * B  A / B  A % B  A ** B
0  10  1     11      9     10   10.0      0      10
1  20  2     22     18     40   10.0      0     400
2  30  3     33     27     90   10.0      0   27000

In [95]:
df["A + 5"] = df["A"] + 5
df["B * 10"] = df["B"] * 10
df

    A  B  A + B  A - B  A * B  A / B  A % B  A ** B  A + 5  B * 10
0  10  1     11      9     10   10.0      0      10     15      10
1  20  2     22     18     40   10.0      0     400     25      20
2  30  3     33     27     90   10.0      0   27000     35      30

In [3]:
df = pd.DataFrame({
    "Name":["A","B","C"],
    "Age":[23,25,21],
    "City":["Delhi" , "Mumbai" , "Chennai"]
})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

## DataType Conversion