In [1]:
import pandas as pd

In [2]:
data={
    'Region':['East','East','East','East','west','west','west','west','South','South','South','South'],
    'Product':['Laptop','Laptop','Moblie','Mobile','Laptop','Laptop','Tablet','Tablet','Moblie','Mobile','Tablet','Tablet'],
    'Sales':[800,500,600,400,1000,700,500,300,650,550,450,350],
    'Quantity':[5,3,4,2,6,4,3,2,5,3,4,2]
}
df=pd.DataFrame(data)
df

   Region Product  Sales  Quantity
0    East  Laptop    800         5
1    East  Laptop    500         3
2    East  Moblie    600         4
3    East  Mobile    400         2
4    west  Laptop   1000         6
5    west  Laptop    700         4
6    west  Tablet    500         3
7    west  Tablet    300         2
8   South  Moblie    650         5
9   South  Mobile    550         3
10  South  Tablet    450         4
11  South  Tablet    350         2

In [5]:
pivot_index = pd.pivot_table(df, index = "Region", values = "Sales" , aggfunc = 'sum')
pivot_index

        Sales
Region
East     2300
South    2000
west     2500

In [7]:
pivot_column = pd.pivot_table(df, index = "Region",columns  = "Product", values = "Sales" , aggfunc = 'sum')
pivot_column

Product  Laptop  Mobile  Moblie  Tablet
Region
East     1300.0   400.0   600.0     NaN
South       NaN   550.0   650.0   800.0
west     1700.0     NaN     NaN   800.0

In [8]:
pivot_fill = pd.pivot_table(df, index = "Region",columns  = "Product", values = "Sales" , aggfunc = 'sum', fill_value = 0)
pivot_fill

Product  Laptop  Mobile  Moblie  Tablet
Region
East       1300     400     600       0
South         0     550     650     800
west       1700       0       0     800

In [9]:
pivot_fill = pd.pivot_table(df, index = "Region",columns  = "Product", values = "Sales" , aggfunc = ['min','max'], fill_value = 0)
pivot_fill

           min                         max
Product Laptop Mobile Moblie Tablet Laptop Mobile Moblie Tablet
Region
East       500    400    600      0    800    400    600      0
South        0    550    650    350      0    550    650    450
west       700      0      0    300   1000      0      0    500

In [10]:
pivot_count = pd.pivot_table(df, index = "Region",columns  = "Product", values = "Sales" , aggfunc = 'count', fill_value = 0)
pivot_count

Product  Laptop  Mobile  Moblie  Tablet
Region
East          2       1       1       0
South         0       1       1       2
west          2       0       0       2

In [12]:
pivot_sum = pd.pivot_table(df, index = "Region",columns  = "Product", values = "Sales" , aggfunc = 'sum', fill_value = 0,margins = True)
pivot_sum

Product  Laptop  Mobile  Moblie  Tablet   All
Region
East       1300     400     600       0  2300
South         0     550     650     800  2000
west       1700       0       0     800  2500
All        3000     950    1250    1600  6800

## Crosstab

In [13]:
data = {
    "Employee":["John","James","David","Mary","Tom","Charlie"],
    "Department":["Sales","HR","Sales","IT","HR","IT"],
    "Gender":["Male","Female","Male","Female","Male","Male"],
    "Salary":[50000,60000,55000,70000,62000,68000]
}
df = pd.DataFrame(data)
df

  Employee Department  Gender  Salary
0     John      Sales    Male   50000
1    James         HR  Female   60000
2    David      Sales    Male   55000
3     Mary         IT  Female   70000
4      Tom         HR    Male   62000
5  Charlie         IT    Male   68000

In [15]:
# count of employees per department X gender

ct = pd.crosstab( index = df["Department"],columns = df["Gender"])
ct

Gender      Female  Male
Department
HR               1     1
IT               1     1
Sales            0     2

In [17]:
ct_sum = pd.crosstab(index = df["Department"],columns = df["Gender"],values = df["Salary"],aggfunc = "sum")
ct_sum

Gender       Female      Male
Department
HR          60000.0   62000.0
IT          70000.0   68000.0
Sales           NaN  105000.0

In [21]:
ct_multi = pd.crosstab(index = df["Department"],columns = df["Gender"],values = df["Salary"],aggfunc = ["sum","mean"])
ct_multi

                sum               mean
Gender       Female      Male   Female     Male
Department
HR          60000.0   62000.0  60000.0  62000.0
IT          70000.0   68000.0  70000.0  68000.0
Sales           NaN  105000.0      NaN  52500.0

In [23]:
ct_multi = pd.crosstab(index = df["Department"],columns = df["Gender"],values = df["Salary"],aggfunc = ["sum","mean"],margins = True)
ct_multi

                 sum                       mean
Gender        Female      Male     All   Female     Male           All
Department
HR           60000.0   62000.0  122000  60000.0  62000.0  61000.000000
IT           70000.0   68000.0  138000  70000.0  68000.0  69000.000000
Sales            NaN  105000.0  105000      NaN  52500.0  52500.000000
All         130000.0  235000.0  365000  65000.0  58750.0  60833.333333

In [26]:
ct_norm = pd.crosstab(index = df["Department"],columns = df["Gender"],normalize = "index")
ct_norm

Gender      Female  Male
Department
HR             0.5   0.5
IT             0.5   0.5
Sales          0.0   1.0

## Concatenation

In [48]:
data_a = {
    "EmpId":[1,2],
    "Name":["John","Tom"],
    "Department":["Sales","HR"]
}

data_b = {
    "EmpId":[3,4],
    "Name":["David","Mary"],
    "Department":["IT","Sales"]
}
df_a = pd.DataFrame(data_a)
df_b = pd.DataFrame(data_b)
print(df_a)
print("--------------------------")
print(df_b)

   EmpId  Name Department
0      1  John      Sales
1      2   Tom         HR
--------------------------
   EmpId   Name Department
0      3  David         IT
1      4   Mary      Sales

In [49]:
# Row Wise concatination

row_concat = pd.concat([df_a,df_b],axis = 0,ignore_index = True)
row_concat

   EmpId   Name Department
0      1   John      Sales
1      2    Tom         HR
2      3  David         IT
3      4   Mary      Sales

In [46]:
# column wise

data_a = {
    "EmpId":[1,2],
    "Name":["John","Tom"]
}

data_b = {
    "Department":["IT","Sales"],
    "Salary":[50000,60000]
}
df_a = pd.DataFrame(data_a)
df_b = pd.DataFrame(data_b)
print(df_a)
print("--------------------------")
print(df_b)

   EmpId  Name
0      1  John
1      2   Tom
--------------------------
  Department  Salary
0         IT   50000
1      Sales   60000

In [47]:
col_concat = pd.concat([df_a,df_b] , axis = 1)
col_concat

   EmpId  Name Department  Salary
0      1  John         IT   50000
1      2   Tom      Sales   60000

## Merging

In [53]:
employees = pd.DataFrame({
    "EmpID":[1,2,3,4],
    "EmpName":["A","B","C","D"],
    "DeptID":[101,102,103,104]
})
departments = pd.DataFrame({
    "DeptID":[101,102,103,105],
    "DeptName":["HR","IT","Fincance","Marketing"]
})

print(employees)
print("---------------------------------")
print(departments)

   EmpID EmpName  DeptID
0      1       A     101
1      2       B     102
2      3       C     103
3      4       D     104
---------------------------------
   DeptID   DeptName
0     101         HR
1     102         IT
2     103   Fincance
3     105  Marketing

In [54]:
# Inner Join ---> returns Common rows only
inner_join = pd.merge(employees,departments , on = "DeptID" , how  = 'inner')
print(inner_join)

   EmpID EmpName  DeptID  DeptName
0      1       A     101        HR
1      2       B     102        IT
2      3       C     103  Fincance

In [56]:
# Left Join ---> All employees + matching depts
left_join = pd.merge(employees,departments , on = "DeptID" , how  = 'left')
print(left_join)

   EmpID EmpName  DeptID  DeptName
0      1       A     101        HR
1      2       B     102        IT
2      3       C     103  Fincance
3      4       D     104       NaN

In [57]:
# Right Join ---> All Departmengts + matching employees
right_join = pd.merge(employees,departments , on = "DeptID" , how  = 'right')
print(right_join)

   EmpID EmpName  DeptID   DeptName
0    1.0       A     101         HR
1    2.0       B     102         IT
2    3.0       C     103   Fincance
3    NaN     NaN     105  Marketing

In [58]:
# Outer Join ---> All records from both df's
outer_join = pd.merge(employees,departments , on = "DeptID" , how  = 'outer')
print(outer_join)

   EmpID EmpName  DeptID   DeptName
0    1.0       A     101         HR
1    2.0       B     102         IT
2    3.0       C     103   Fincance
3    4.0       D     104        NaN
4    NaN     NaN     105  Marketing